global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "/etc/prometheus/rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Consul service discovery
  - job_name: 'consul'
    static_configs:
      - targets: ['consul:8500']
    metrics_path: /v1/agent/metrics
    params:
      format: ['prometheus']

  # Hub Server
  - job_name: 'hub-server'
    consul_sd_configs:
      - server: 'consul:8500'
        services: ['fin-hub-registry']
    relabel_configs:
      - source_labels: [__meta_consul_service]
        target_label: job
      - source_labels: [__meta_consul_node]
        target_label: instance
    metrics_path: /metrics
    scrape_interval: 30s

  # Market Spoke
  - job_name: 'market-spoke'
    static_configs:
      - targets: ['market-spoke:8000']
    metrics_path: /metrics
    scrape_interval: 30s

  # Risk Spoke
  - job_name: 'risk-spoke'
    static_configs:
      - targets: ['risk-spoke:8000']
    metrics_path: /metrics
    scrape_interval: 30s

  # Portfolio Spoke
  - job_name: 'pfolio-spoke'
    static_configs:
      - targets: ['pfolio-spoke:8000']
    metrics_path: /metrics
    scrape_interval: 30s

  # NGINX Gateway
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']
    metrics_path: /stub_status
    scrape_interval: 30s

  # Redis
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    metrics_path: /metrics
    scrape_interval: 30s

  # PostgreSQL
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    metrics_path: /metrics
    scrape_interval: 30s

  # Node Exporter (system metrics)
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s